factura/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'ventas.views.main'),
    url(r'^login/$', 'ventas.views.login_user'),
    url(r'^logout/$', 'ventas.views.logout_user'),
    url(r'^register/$', 'ventas.views.register_user'),
    url(r'^empresa/$',  'ventas.views.index_empresa'),
    url(r'^empresa/add/$', 'ventas.views.add_empresa'),
    url(r'^empresa/edit/(?P<pk>\d+)$', 'ventas.views.edit_empresa'),
    url(r'^empresa/delete/(?P<pk>\d+)$', 'ventas.views.delete_empresa'),
    url(r'^categoria/$',  'ventas.views.index_categoria'),
    url(r'^categoria/add/$', 'ventas.views.add_categoria'),
    url(r'^categoria/edit/(?P<pk>\d+)$', 'ventas.views.edit_categoria'),
    url(r'^categoria/delete/(?P<pk>\d+)$', 'ventas.views.delete_categoria'),
    url(r'^tipodoc/$',  'ventas.views.index_tipodoc'),
    url(r'^tipodoc/add/$', 'ventas.views.add_tipodoc'),
    url(r'^tipodoc/edit/(?P<pk>\d+)$', 'ventas.views.edit_tipodoc'),
    url(r'^tipodoc/delete/(?P<pk>\d+)$', 'ventas.views.delete_tipodoc'),
    url(r'^tipocaja/$',  'ventas.views.index_tipocaja'),
    url(r'^tipocaja/add/$', 'ventas.views.add_tipocaja'),
    url(r'^tipocaja/edit/(?P<pk>\d+)$', 'ventas.views.edit_tipocaja'),
    url(r'^tipocaja/delete/(?P<pk>\d+)$', 'ventas.views.delete_tipocaja'),
    url(r'^cuentabanco/$',  'ventas.views.index_cuentabanco'),
    url(r'^cuentabanco/add/$', 'ventas.views.add_cuentabanco'),
    url(r'^cuentabanco/edit/(?P<pk>\d+)$', 'ventas.views.edit_cuentabanco'),
    url(r'^cuentabanco/delete/(?P<pk>\d+)$', 'ventas.views.delete_cuentabanco'),
    url(r'^formapago/$',  'ventas.views.index_formapago'),
    url(r'^formapago/add/$', 'ventas.views.add_formapago'),
    url(r'^formapago/edit/(?P<pk>\d+)$', 'ventas.views.edit_formapago'),
    url(r'^formapago/delete/(?P<pk>\d+)$', 'ventas.views.delete_formapago'),
    url(r'^banco/$',  'ventas.views.index_banco'),
    url(r'^banco/add/$', 'ventas.views.add_banco'),
    url(r'^banco/edit/(?P<pk>\d+)$', 'ventas.views.edit_banco'),
    url(r'^banco/delete/(?P<pk>\d+)$', 'ventas.views.delete_banco'),
    #url(r'^banco/bulk$',  'ventas.views.bulk_insert'),
    url(r'^tipoimpuesto/$',  'ventas.views.index_tipoimpuesto'),
    url(r'^tipoimpuesto/add/$', 'ventas.views.add_tipoimpuesto'),
    url(r'^tipoimpuesto/edit/(?P<pk>\d+)$', 'ventas.views.edit_tipoimpuesto'),
    url(r'^tipoimpuesto/delete/(?P<pk>\d+)$', 'ventas.views.delete_tipoimpuesto'),    
    url(r'^articulo/$',  'ventas.views.index_articulo'),
    url(r'^articulo/add/$', 'ventas.views.add_articulo'),
    url(r'^articulo/edit/(?P<pk>\d+)$', 'ventas.views.edit_articulo'),
    url(r'^articulo/delete/(?P<pk>\d+)$', 'ventas.views.delete_articulo'),
    url(r'^articulo/search/$', 'ventas.views.search_articulo'),
    url(r'^articulo/searchcode/$', 'ventas.views.search_articulo_codigo'),
    url(r'^cliente/$',  'ventas.views.index_cliente'),
    url(r'^cliente/add/$', 'ventas.views.add_cliente'),
    url(r'^cliente/qadd/$', 'ventas.views.qadd_cliente'),
    url(r'^cliente/edit/(?P<pk>\d+)$', 'ventas.views.edit_cliente'),
    url(r'^cliente/delete/(?P<pk>\d+)$', 'ventas.views.delete_cliente'),
    url(r'^cliente/search/$', 'ventas.views.search_cliente'),
    url(r'^cliente/searchid/$', 'ventas.views.search_cliente_id'),
    url(r'^proveedor/$',  'ventas.views.index_proveedor'),
    url(r'^proveedor/add/$', 'ventas.views.add_proveedor'),
    url(r'^proveedor/edit/(?P<pk>\d+)$', 'ventas.views.edit_proveedor'),
    url(r'^proveedor/delete/(?P<pk>\d+)$', 'ventas.views.delete_proveedor'),
    url(r'^proveedor/search/$', 'ventas.views.search_proveedor'),
    url(r'^proveedor/searchid/$', 'ventas.views.search_proveedor_id'),
    url(r'^factura/$',  'ventas.views.index_factura'),
    url(r'^factura/add/$', 'ventas.views.add_factura'),
    url(r'^factura/edit/(?P<pk>\d+)$', 'ventas.views.edit_factura'),
    url(r'^factura/delete/(?P<pk>\d+)$', 'ventas.views.delete_factura'),
    url(r'^detalle/(?P<pk>\d+)$', 'ventas.views.detalle'),
    url(r'^detalle/delete/(?P<pk>\d+)/(?P<fact>\d+)/$', 'ventas.views.delete_detalle'),    
    url(r'^postext/$',  'ventas.views.postext'),
    url(r'^postext/addline/$',  'ventas.views.add_postext'),
    url(r'^postext/delline/$',  'ventas.views.del_postext'),
    url(r'^postext/addcobro/$',  'ventas.views.add_cobro'),
    url(r'^postext/delcobro/$',  'ventas.views.del_cobro'),
    url(r'^factcompra/$',  'ventas.views.index_factcompra'),
    url(r'^factcompra/add/$', 'ventas.views.add_factcompra'),
    url(r'^factcompra/edit/(?P<pk>\d+)$', 'ventas.views.edit_factcompra'),
    url(r'^factcompra/delete/(?P<pk>\d+)$', 'ventas.views.delete_factcompra'),
    url(r'^detallefc/(?P<pk>\d+)$', 'ventas.views.detallefc'),
    url(r'^detallefc/delete/(?P<pk>\d+)/(?P<fact>\d+)/$', 'ventas.views.delete_detallefc'),    
    url(r'^opencaja/$',  'ventas.views.opencaja'),
    url(r'^closecaja/$',  'ventas.views.closecaja'),
    url(r'^movcaja/$',  'ventas.views.movcaja'),
    url(r'^movcaja/add/$',  'ventas.views.add_movcaja'),
    url(r'^movcaja/sub/$',  'ventas.views.sub_movcaja'),
    url(r'^movcaja/search/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$',  'ventas.views.search_movcaja' ,name='search_mc'),
    url(r'^openturno/$',  'ventas.views.openturno'),
    url(r'^closeturno/$',  'ventas.views.closeturno'),
    url(r'^inventario/$',  'ventas.views.index_inventario'),
    url(r'^inventario/add/$',  'ventas.views.add_inventario'),
    url(r'^inventario/search/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$',  'ventas.views.search_inventario' ,name='search_inv'),
    #url(r'^inventario/search/$',  'ventas.views.search_inventario', name='search_inv'),
    url(r'^reportes/inventario/$',  'ventas.views.rptinventarios'),
    url(r'^reportes/ventas/$',  'ventas.views.ventas'),
    url(r'^reportes/compras/$',  'ventas.views.rptcompras'),
]

ventas/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import *
from django.db.models.signals import pre_save, post_save, post_delete
from django.dispatch import receiver
from django.contrib.auth.models import User
# Create your models here.
# into your database.

class Empresa(models.Model):    
    razon_social = models.CharField(max_length=200, blank=False, null=True)
    direccion = models.CharField(max_length=500, blank=True, null=True)
    rif = models.CharField(max_length=15, blank=True, null=True)
    nit = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    tlf = models.CharField(max_length=45, blank=True, null=True)
    fax = models.CharField(max_length=45, blank=True, null=True)
    ruta_foto = models.ImageField(upload_to='empresas/', null=True)
    p1 = models.CharField(max_length=25, blank=True, null=True)
    p2 = models.CharField(max_length=25, blank=True, null=True)
    p3 = models.CharField(max_length=25, blank=True, null=True)
    p4 = models.CharField(max_length=25, blank=True, null=True)
    p5 = models.CharField(max_length=25, blank=True, null=True)

    class Meta:        
        db_table = 'empresa'

    def __unicode__(self):
        return self.razon_social

class TipoImpuesto(models.Model):
    nombre       = models.CharField(max_length=50, blank=False, null=True)    
    codigo       = models.CharField(max_length=50, blank=False, null=True)    
    valido_desde = models.DateField( blank=False, null=False)
    valido_hasta = models.DateField( blank=True, null=True)
    valor        = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default="0.00")    

    class Meta:        
        db_table = 'tipo_impuesto'

    def __unicode__(self):
        return "(%s) - %s" % (self.codigo, self.valor)


class Categoria(models.Model):
    nombre = models.CharField(max_length=250, blank=False, null=False)
    ruta_foto = models.ImageField(upload_to='categorias/', null=True)

    class Meta:        
        db_table = 'categoria'

    def __unicode__(self):
        return self.nombre
        
class Articulo(models.Model):
    codigo = models.CharField(max_length=50, blank=False, null=True)    
    descripcion = models.CharField(max_length=250, blank=False, null=True)    
    importe = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True, default="0.00")
    descuento = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default="0.00")    
    inventar = models.NullBooleanField(null=False)
    #impuesto = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default="0.00")        
    ruta_foto = models.ImageField(upload_to='articulos/', null=True)
    categoria = models.ForeignKey('Categoria')
    tipoimpuesto = models.ForeignKey('TipoImpuesto', null=True)

    class Meta:        
        db_table = 'articulo'
    
    def __unicode__(self):
        return self.descripcion

class Cliente(models.Model):
    nombre = models.CharField(max_length=200, blank=True, null=True)
    razon_social = models.CharField(max_length=200, blank=False, null=False)
    direccion = models.CharField(max_length=500, blank=False, null=True)
    rif = models.CharField(max_length=15, blank=False, null=False)
    nit = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    tlf = models.CharField(max_length=45, blank=True, null=True)
    fax = models.CharField(max_length=45, blank=True, null=True)        

    class Meta:        
        db_table = 'cliente'
    
    def __unicode__(self):
        return self.razon_social


class Banco(models.Model):
    nombre = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        db_table = 'banco'

    def __unicode__(self):
        return self.nombre

class TipoDoc(models.Model):
    codigo = models.CharField(max_length=2, blank=True, null=True)   
    nombre = models.CharField(max_length=45, blank=True, null=True)
    correlativo = models.IntegerField(blank=True, null=True)

    class Meta:        
        db_table = 'tipo_doc'
    
    def __unicode__(self):
        return self.nombre

class Proveedor(models.Model):
    nombre = models.CharField(max_length=200, blank=True, null=True)
    razon_social = models.CharField(max_length=200, blank=True, null=True)
    direccion = models.CharField(max_length=500, blank=True, null=True)
    rif = models.CharField(max_length=15, blank=True, null=True)
    nit = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    tlf = models.CharField(max_length=45, blank=True, null=True)
    fax = models.CharField(max_length=45, blank=True, null=True)
    ruta_foto = models.ImageField(upload_to='proveedores/', null=True)

    class Meta:        
        db_table = 'proveedor'

    def __unicode__(self):
        return self.razon_social

class Documento(models.Model):
    correlativo = models.IntegerField(blank=True, null=True)
    fecha = models.DateField(default=datetime.now,blank=True)
    fecha_vencimiento = models.DateField(default=datetime.now,blank=True)
    fecha_hora = models.DateTimeField(default=datetime.now,blank=True)
    contacto = models.CharField(max_length=45, blank=True, null=True)
    nota_superior = models.CharField(max_length=500, blank=True, null=True)
    nota_detalle = models.CharField(max_length=500, blank=True, null=True)
    referencia = models.IntegerField(blank=True, null=True)    
    tipo_doc = models.ForeignKey(TipoDoc,blank=False, null=True)
    proveedor = models.ForeignKey(Proveedor, blank=False, null=True)
    cliente = models.ForeignKey(Cliente, blank=False, null=True)
    total_general = models.DecimalField(blank=True, null=True,max_digits=10, decimal_places=2,default=0.00)
    pct_descuento = models.DecimalField(blank=True, null=True,max_digits=5, decimal_places=2,default=0.00)    
    pct_impuesto  = models.DecimalField(blank=True, null=True,max_digits=5, decimal_places=2,default=0.00)    
    subtotal = models.DecimalField(blank=True, null=True,max_digits=10, decimal_places=2,default=0.00)
    tot_impuesto = models.DecimalField(blank=True, null=True,max_digits=10, decimal_places=2,default=0.00)
    excento = models.DecimalField(blank=True, null=True,max_digits=10, decimal_places=2,default=0.00)
    imponible = models.DecimalField(blank=True, null=True,max_digits=10, decimal_places=2,default=0.00)
    tot_descuento = models.DecimalField(blank=True, null=True,max_digits=10, decimal_places=2,default=0.00)
    sujeto_dcto = models.DecimalField(blank=True, null=True,max_digits=10, decimal_places=2,default=0.00)
    estado  = models.NullBooleanField(null=False,default=False)
    usuario = models.ForeignKey(User)

    class Meta:        
        db_table = 'documento'

    
class DocumentoDet(models.Model):
    descripcion = models.CharField(max_length=200, blank=True, null=True)
    cantidad = models.IntegerField(blank=False, null=True,default=1)
    importe = models.DecimalField(blank=True, null=True,max_digits=10, decimal_places=2,default=0.00)
    descuento = models.DecimalField(blank=True, null=False,max_digits=5, decimal_places=2,default=0.00)
    impuesto = models.DecimalField(blank=True, null=True,max_digits=5, decimal_places=2,default=0.00)    
    total = models.DecimalField(blank=True, null=True,max_digits=10, decimal_places=2,default=0.00)
    nota = models.CharField(max_length=45, blank=True, null=True)
    documento = models.ForeignKey(Documento)
    item = models.ForeignKey(Articulo)

    class Meta:        
        db_table = 'documento_det'


class FormaPago(models.Model):
    nombre = models.CharField(max_length=45, blank=True, null=True)
    efectivo = models.NullBooleanField(null=False,default=False)
    monetizable = models.NullBooleanField(null=False,default=True)

    class Meta:        
        db_table = 'forma_pago'
    
    def __unicode__(self):
        return self.nombre

class Cobros(models.Model):
    fecha = models.DateField(default=datetime.now,blank=True)
    fecha_hora = models.DateTimeField(default=datetime.now,blank=True)
    aprobacion = models.CharField(max_length=45, blank=True, null=True)
    monto = models.DecimalField(blank=True, null=True,max_digits=9, decimal_places=2)
    descripcion = models.CharField(max_length=45, blank=True, null=True)    
    forma_pago = models.ForeignKey(FormaPago)
    documento = models.ForeignKey(Documento)
    banco = models.ForeignKey(Banco, blank=True, null=True)
    usuario = models.ForeignKey(User)
    estado  = models.NullBooleanField(null=False,default=False)

    class Meta:        
        db_table = 'cobros'


class Pagos(models.Model):
    fecha = models.DateField(blank=True, null=True)
    fecha_hora = models.DateTimeField(default=datetime.now,blank=True)
    aprobacion = models.CharField(max_length=45, blank=True, null=True)
    monto = models.DecimalField(blank=True, null=True,max_digits=9, decimal_places=2)
    descripcion = models.CharField(max_length=45, blank=True, null=True)
    documento = models.ForeignKey(Documento)
    forma_pago = models.ForeignKey(FormaPago)
    banco = models.ForeignKey(Banco, blank=True, null=True)
    usuario = models.ForeignKey(User)

    class Meta:        
        db_table = 'pagos'


class Inventario(models.Model):
    tipo = models.CharField(max_length=1)
    descripcion = models.CharField(max_length=45, blank=True, null=True)
    fecha = models.DateField(default=datetime.now,blank=True)
    fecha_hora = models.DateTimeField(default=datetime.now,blank=True)
    cantidad = models.BigIntegerField(blank=False, null=False, default=1)    
    articulo = models.ForeignKey(Articulo) 
    usuario = models.ForeignKey(User)

    class Meta:        
        db_table = 'inventario'
    
    def __unicode__(self):
        return self.descripcion

    @receiver(post_save, sender=DocumentoDet)

ventas/templates/detalle.html
{% extends "base.html" %}
{% load humanize %}
{% block main %}
			<div class="page-header">
				<h1>
					Sistema de Facturacion <small>Detalle</small>
				</h1>
			</div>

						<!-Datos de la factura->
            <div class="col-sm-6">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title">
                  Factura
                </h3>
              </div>
				    <div class="col-sm-6"><h4>Factura:</h4></div>
            <div class="col-sm-6"><h4> {{ factura.correlativo }} </h4></div>
				    <div class="col-sm-6"><h4>Cliente: </h4></div>
            <div class="col-sm-6"><h4>{{ factura.cliente }} </h4></div>
				    <div class="col-sm-6"><h4>Rif:</h4></div>
            <div class="col-sm-6"><h4> {{ factura.cliente.rif }} </h4></div>
				    <div class="col-sm-6"><h4>Fecha: </h4></div>
            <div class="col-sm-6"><h4>{{ factura.fecha }} </h4></div>
             </div>
            </div>
            <!-Totales factura->
            
            <div class="col-sm-6">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title">
                  Totales
                </h3>
              </div>

            <div class="col-sm-6">
            <h4>Subtotal</h4>
            </div>
            <div class="col-sm-6">
            <h4>{{ data.subtotal |floatformat:"2"|intcomma}}</h4>
            </div>    

            {% if data.excento %}
            <div class="col-sm-6">
            <h4>Total Excento</h4>
            </div>    
            <div class="col-sm-6">
            <h4> {{ data.excento |floatformat:"2"|intcomma}}</h4>
            </div>    
            {% endif %}
          
          {% if data.sujeto_dcto %}
            <div class="col-sm-6">
            <h5>Dto. {{ data.pct_descuento }}% sobre {{data.sujeto_dcto |floatformat:"2"|intcomma}} </h5>
            </div>    
            <div class="col-sm-6">            
            <h4> {{ data.tot_descuento |floatformat:"2"|intcomma}}</h4>
            </div>            
          {% endif %}

          {% if data.imponible %}          
            <div class="col-sm-6">            
            <h4>Base Imponible</h4>         
            </div>            
            <div class="col-sm-6">            
            <h4> {{ data.imponible |floatformat:"2"|intcomma }}</h4>    
            </div>            
            <div class="col-sm-6">                  
            <h5>I.V.A{{ data.pct_impuesto }}% sobre {{ data.imponible |floatformat:"2"|intcomma}}</h5>          
            </div>            
            <div class="col-sm-6">            
            <h4> {{ data.tot_impuesto |floatformat:"2"|intcomma}}</h4>      
            </div>            
          {% endif %}
            <div class="col-sm-6">            
            <h3>Total General</h3>          
            </div>
            <div class="col-sm-6">                          
            <h3> {{ data.total_general|floatformat:"2"|intcomma }}</h3>          
            </div>
          </div>
       </div>

				    <div class="col-sm-12"> <center>				
								<button type="button" class="btn btn-primary btn-lg" onclick="window.location.href='/factura/'">Salir</button></center>	
            </div>          		

								    
			
			<div class="col-sm-12"><hr></div>
			<table class="table table-hover table-condensed">	 
  		<tr><th>Articulo</th><th>Cantidad</th><th>Importe</th><th>Descuento</th><th>Impuesto</th><th>Total</th><th>Accion</th></tr>
  					<tr>
  					<form method="post" class="form" enctype="multipart/form-data" id="myform" name="myform">
  						{% csrf_token %}  						
						{% for field in form %}				        
							{% if field.label = 'Item' %}							
							<td> <div class="ui-widget">
							       <input id="search" class="special" type="text" size="10" name="search" autocomplete="off"> {{ field }} 
							     </div>
              </td>					  
							{% else %}
							 <td> {{ field }}  </td>
							{% endif %}              
						{% endfor %}
						     <td> <button type="submit" class="btn btn-default" >Agregar</button></td>     
						 </form>
						</tr>
            <tr>
            {% for field in form %}              
                <td>
                  {% if field.errors %}
                 <div class="alert alert-danger" role="alert">{{ field.errors }}</div>
                 {% endif %}
                </td>
              
            {% endfor %}
            </tr>
                      
	    {% for linea in lineas %}
	        <tr>
	        	<td>{{ linea.item }}</td>	        	
	        	<td>{{ linea.cantidad }}</td>	        	
	        	<td>{{ linea.importe }}</td>	
	        	<td>{{ linea.descuento }}</td>	
            	<td>{{ linea.impuesto }}</td>
            	<td>{{ linea.total }}</td>
            	
	        <td>	        	        
	        <a href="delete/{{linea.pk}}/{{ id }}"> <img src="/media/icons/close_32.png"\> </a>
	        </td>
	        	
	        </tr>
	        	        
	        {% empty %}
	    	   <tr><td colspan="4">
	    	    <h3>No se encontraron registros</h3>	    
	    	    </td></tr>
	    	{% endfor %}


	</table>

<script>

$(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});

$( document ).ready(function() {
   /*$('#id_importe').prop( "disabled", true );
   $('#id_impuesto').prop( "disabled", true );
   $('#id_total').prop( "disabled", true );*/
   $('#id_documento').val({{ id }});

});

/*$(document).ready(function(){ 
    $("#myform").submit(function(event){         
            event.preventDefault(); 
    }); 
});*/

$( "#id_cantidad" )
  .change(function () {

  	make_calculations()

  })
  .change();

$( "#id_descuento" )
  .change(function () {

  	make_calculations()

  })
  .change();


function make_calculations(){
        
    sub_imp=($('#id_cantidad').val() * $('#id_importe').val())*($('#id_impuesto').val()/100)
    sub_dct=($('#id_cantidad').val() * $('#id_importe').val())*($('#id_descuento').val()/100)
    total=$('#id_cantidad').val() * $('#id_importe').val()
    
    $('#id_total').val(total);          

}

  $(function() {    
 
    $( "#search" ).autocomplete({
      source: "/articulo/search/",
      minLength: 2,
      select: function( event, ui ) {
        //console.log(ui.item + ui.item.value + ui.item.id);
        //sub_imp=ui.item.importe*(ui.item.impuesto/100)
        //sub_dct=ui.item.importe*(ui.item.descuento/100)

        $('#id_importe').val(ui.item.importe);
        $('#id_descuento').val(ui.item.descuento);
        $('#id_impuesto').val(ui.item.impuesto);
        //$('#id_total').val(total);
        make_calculations();
        $('#id_item').val(ui.item.id);
      }
    });
  });

/*
var para2={{data_json}};
//console.log(para2);

var params = [];
for (var key in para2) {
  if (para2.hasOwnProperty(key)) {
    params.push({
        "name": key,
        "value": para2[key]
        })  
  }
}

//console.log(params);

$('#myform').submit(function () {
    $(this).append($.map(params, function (param) {
        return   $('<input>', {
            type: 'hidden',
            name: param.name,
            value: param.value,
        })
    }))
});

*/
//var params = []
//console.log({{data_json}});

  </script>

{% endblock %}
  

ventas/templates/factura.html
{% extends "base.html" %}

{% block main %}
			<div class="page-header">
				<h1>
					Sistema de Facturacion <small>Factura</small>
				</h1>
			</div>

			<h2>
				Factura
			</h2>
			<p>
				<form method="post" class="form" enctype="multipart/form-data" >
				    {% csrf_token %}
	    			<table class="table ">	 
	    				<tr>
	    					<td>{{form.cliente.label_tag}}</td>
	    					<td colspan="3">
	    						<div class="ui-widget">
							       <input id="search" class="special" type="text" size="33" name="search" autocomplete="off"> {{ form.cliente }} 
							     </div>
	    					{% if form.cliente.errors %}
        				 	<div class="alert alert-danger" role="alert">{{ form.cliente.errors }}</div>        				 	
        					{% endif %}
        					</td>
	    				</tr>
	    				
	    				<tr>	    				
	    					<td>{{form.fecha.label_tag}}</td>
	    					<td>{{form.fecha}}
	    					  {% if form.fecha.errors %}				         	
        				 	  <div class="alert alert-danger" role="alert">{{ form.fecha.errors }}</div> {% endif %}
        				 	</td>
	    					<td>{{form.fecha_vencimiento.label_tag}}</td>
	    					<td>{{form.fecha_vencimiento}}
	    					 {% if form.fecha_vencimiento.errors %}				         	
        				 	  <div class="alert alert-danger" role="alert">{{ form.fecha_vencimiento.errors }}</div> {% endif %}
	    					</td>
	    				</tr>


	    				<tr>	    				
	    					<td>{{form.nota_superior.label_tag}}</td>
	    					<td>{{form.nota_superior}}</td>
	    					<td>{{form.nota_detalle.label_tag}}</td>
	    					<td>{{form.nota_detalle}}</td>
	    				</tr>
	    				<tr>
	    					<td>{{form.contacto.label_tag}}</td>
	    					<td colspan="3">{{form.contacto}}</td>
	    				</tr>
	    				<tr>	    					
	    					<td colspan="4" align="center">
	    					<div class="form-group">
							<div class="col-sm-12"> <button type="submit" class="btn btn-primary btn-lg">Enviar</button></div>
							</div>  
	    					</td>
	    				</tr>

	    			</table>	 				    

				      
				    
				</form>
			</p>
		
 <script>
  $(function() {
    $( "#id_fecha" ).datepicker({ dateFormat: 'yy-mm-dd' });
    $( "#id_fecha_vencimiento" ).datepicker({ dateFormat: 'yy-mm-dd' });
    write_client_name();
  });


  $(function() {    
 
    $( "#search" ).autocomplete({
      source: "/cliente/search/",
      minLength: 3,
      select: function( event, ui ) {
        //console.log(ui.item + ui.item.value + ui.item.id);            
        $('#id_cliente').val(ui.item.id);
      }
    });
  });


function write_client_name() {
    //console.log("create post is working!") // sanity check
    $.ajax({
        url : "/cliente/searchid/", // the endpoint
        type : "GET", // http method
        data : { search : $('#id_cliente').val() }, // data sent with the post request

        // handle a successful response
        success : function(json) {               	        	
			//console.log(json.cliente.razon_social);
			razon=json.cliente.razon_social;
            $('#search').val(razon);            
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {        
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the 
        }
    });
};



  </script>

{% endblock %}